#!/bin/bash
if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit
fi

cp etc/systemd/system/* /etc/systemd/system/
cp usr/local/bin/autopm /usr/local/bin/
chmod +x /usr/local/bin/autopm
systemctl enable --now autopm
